---
- hosts: localhost
  connection: local
  ignore_unreachable: yes
  vars:
    username: janina
    ssh_key_path: "/home/janina/.ssh/ansible.pub"
    linux_slaves:
      - 192.168.178.71
      - 192.168.178.72
    windows_slaves:
      - 192.168.178.74
      - 192.168.178.75
      - 192.168.178.79
      - 192.168.178.80
      - 192.168.178.81

  tasks:
    - name: Read SSH key using sudo
      command: sudo -u janina cat {{ ssh_key_path }}
      register: ssh_key_content

    - name: Set SSH key fact
      set_fact:
        ssh_key: "{{ ssh_key_content.stdout }}"

    - name: Copy SSH key to Linux slaves
      ignore_unreachable: yes
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
      loop: "{{ linux_slaves }}"
      delegate_to: "{{ item }}"


    - name: Add Linux slaves to known_hosts
      known_hosts:
        name: "{{ item }}"
        key: "{{ ssh_key }}"
        state: present
        hash_host: yes
      loop: "{{ linux_slaves }}"
      ignore_errors: yes


    - name: Add Windows slaves to known_hosts
      known_hosts:
        name: "{{ item }}"
        key: "{{ ssh_key }}"
        state: present
        hash_host: yes
      loop: "{{ windows_slaves }}"
      ignore_errors: yes

# Windows


- hosts: windows_slaves
  ignore_unreachable: yes
  gather_facts: no
  vars:
    username: janina
    ssh_key_path: "/home/janina/.ssh/ansible.pub"
  tasks:



    - name: Read SSH key using sudo
      command: sudo -u janina cat {{ ssh_key_path }}
      register: ssh_key_content

    - name: Set SSH key fact
      set_fact:
        ssh_key: "{{ ssh_key_content.stdout }}"



    - name: Get USERPROFILE environment variable
      win_shell: echo $env:USERPROFILE
      register: userprofile_env

    - name: Debug userprofile_env
      debug:
        var: userprofile_env

    - name: Create a directory on Windows
      win_file:
        path: "{{ userprofile_env.stdout.strip() }}\\.ssh"
        state: directory

    - name: Debug directory creation
      debug:
        msg: "Directory created at {{ userprofile_env.stdout.strip() }}\\.ssh"

    - name: Create the authorized key file
      win_file:
        path: "{{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"
        state: touch

    - name: Debug key file creation
      debug:
        msg: "Authorized key file created at {{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"

    - name: Copy a file to Windows
      win_copy:
        src: home/janina/.ssh/ansible.pub
        dest: "{{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"

    - name: Debug file copy
      debug:
        msg: "File copied to {{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"

