---
- name: Distribute SSH keys to Linux and Windows slaves
  hosts: localhost
  connection: local
  vars:
    username: janina
    ssh_key_path: "/home/janina/.ssh/ansible.pub"
    linux_slaves:
      - 192.168.178.71
      - 192.168.178.72
    windows_slaves:
      - 192.168.178.74
      - 192.168.178.75
      - 192.168.178.79
      - 192.168.178.80
      - 192.168.178.81

  tasks:
    - name: Read SSH key using sudo
      command: sudo -u janina cat {{ ssh_key_path }}
      register: ssh_key_content

    - name: Set SSH key fact
      set_fact:
        ssh_key: "{{ ssh_key_content.stdout }}"

    - name: Copy SSH key to Linux slaves
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
      loop: "{{ linux_slaves }}"
      delegate_to: "{{ item }}"

    - name: Add Linux slaves to known_hosts
      known_hosts:
        name: "{{ item }}"
        state: present
      loop: "{{ linux_slaves }}"

    - name: Ensure .ssh directory exists on Windows slaves
      win_file:
        path: "C:\\Users\\{{ username }}\\.ssh"
        state: directory
      loop: "{{ windows_slaves }}"
      delegate_to: "{{ item }}"

    - name: Copy SSH key to Windows slaves
      win_copy:
        content: "{{ ssh_key }}"
        dest: "C:\\Users\\{{ username }}\\.ssh\\authorized_keys"
      loop: "{{ windows_slaves }}"
      delegate_to: "{{ item }}"

    - name: Add Windows slaves to known_hosts
      known_hosts:
        name: "{{ item }}"
        state: present
      loop: "{{ windows_slaves }}"