---
- hosts: localhost
  connection: local
  ignore_unreachable: yes
  vars:
    username: janina
    ssh_key_path: "/home/janina/.ssh/ansible.pub"
    linux_slaves:
      - 192.168.178.71
      - 192.168.178.72
    windows_slaves:
      - 192.168.178.74
      - 192.168.178.75
      - 192.168.178.79
      - 192.168.178.80
      - 192.168.178.81

  tasks:
    - name: Read SSH key using sudo
      command: sudo -u janina cat {{ ssh_key_path }}
      register: ssh_key_content

    - name: Set SSH key fact
      set_fact:
        ssh_key: "{{ ssh_key_content.stdout }}"

    - name: Copy SSH key to Linux slaves
      ignore_unreachable: yes
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
      loop: "{{ linux_slaves }}"
      delegate_to: "{{ item }}"






- hosts: windows_slaves
  ignore_unreachable: yes
  gather_facts: no
  tasks:
    - name: Get USERPROFILE environment variable
      win_shell: echo $env:USERPROFILE
      register: userprofile_env

    - name: Debug userprofile_env
      debug:
        var: userprofile_env

    - name: Create a directory on Windows
      win_file:
        path: "{{ userprofile_env.stdout.strip() }}\\.ssh"
        state: directory

    - name: Create the authorized key file
      win_file:
        path: "{{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"
        state: touch

    - name: Ensure the ansible.pub file exists on the control node
      stat:
        path: /home/janina/.ssh/ansible.pub
      delegate_to: localhost
      register: ansible_pub_file

    - name: Debug ansible.pub file existence
      debug:
        var: ansible_pub_file
      delegate_to: localhost

    - name: Read content of ansible.pub
      command: cat /home/janina/.ssh/ansible.pub
      delegate_to: localhost
      register: ansible_pub_content
      when: ansible_pub_file.stat.exists

    - name: Copy public key content to Windows
      win_lineinfile:
        path: "{{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"
        line: "{{ ansible_pub_content.stdout }}"
        create: yes
      when: ansible_pub_file.stat.exists

    - name: Debug file copy
      debug:
        msg: "Public key content copied to {{ userprofile_env.stdout.strip() }}\\.ssh\\authorized_keys"
      when: ansible_pub_file.stat.exists





- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    linux_slaves:
      - 192.168.178.71
      - 192.168.178.72
    windows_slaves:
      - 192.168.178.74
      - 192.168.178.75
      - 192.168.178.79
      - 192.168.178.80
      - 192.168.178.81
    all_slaves: "{{ linux_slaves + windows_slaves }}"

  tasks:
    - name: Scan SSH keys for all slaves
      command: ssh-keyscan -H -t ed25519 {{ item }}
      register: ssh_keys
      loop: "{{ all_slaves }}"
      ignore_errors: yes

    - name: Add all slaves to known_hosts
      known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout }}"
        state: present
      loop: "{{ ssh_keys.results }}"
      when: item.rc == 0
      ignore_errors: yes

    - name: Debug known_hosts additions
      debug:
        msg: "Added {{ item.item }} to known_hosts"
      loop: "{{ ssh_keys.results }}"
      when: item.rc == 0