---
- hosts: linux_slaves
  ignore_unreachable: yes
  become: true
  tasks:

    - name: create ansible user on Linux
      tags: always
      user:
        name: ansible
        groups: root

    - name: add ssh-key for ansible
      tags: always
      authorized_key:
         user: ansible
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID4uZMBl5Kw9+tH5UZmv6ByQgycS0dfDnb1psDDttJQp ansible"

    - name: add sudoers file for ansible
      tags: always
      copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440



- hosts: windows_slaves
  gather_facts: no
  ignore_unreachable: yes
  tasks:
    - name: Create a new Adminuser ansible on Windows
      win_user:
        name: ansible
        password: 'passworti'
        state: present
        groups:
          - Administrators
          - Administratoren
        password_never_expires: yes
        account_disabled: no
        user_cannot_change_password: no
