---
- hosts: linux_slaves
  become: true
  tasks:

    - name: create simone user on Linux
      tags: always
      user:
        name: simone
        groups: root

    - name: add ssh-key for simone
      tags: always
      authorized_key:
         user: simone
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID4uZMBl5Kw9+tH5UZmv6ByQgycS0dfDnb1psDDttJQp ansible"

    - name: add sudoers file for simone
      tags: always
      copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440



- hosts: windows_slaves
  gather_facts: no
  tasks:
    - name: Create a new Adminuser simone on Windows
      win_user:
        name: simone
        password: 'passwort'
        state: present
        groups:
          - Administrators
        password_never_expires: yes
        account_disabled: no
        user_cannot_change_password: no
