---
- hosts: linux_slaves
  gather_facts: no
  become: true
  tasks:
    - name: install apache2 and php packages on Ubuntu
      tags: apache, apache2, php, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"