---
- hosts: linux_slaves
  become: true
  become_method: sudo
  tasks:
    - name: install apache2 and php packages on Ubuntu
      tags: apache, apache2, php, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: windows_slaves
  gather_facts: no
  tasks:
    - name: install adobe chrome and firefox on windows
      win_chocolatey: 
        name: 
          - adobereader
          - googlechrome
          - firefox
        state: present