---
- name: Copy Ansible SSH-Key to windows
  hosts: windows_slaves
  gather_facts: no

  tasks:
    - name: Ping Windows clients
      win_ping:

    - name: Create a directory on Windows
      win_file:
        path: "C:\\%USERPROFILE%\\.ssh"
        state: directory

    - name: Create the authorized key file
      win_file:
        path: "C:\\%USERPROFILE%\\.ssh\\authorized_keys"
        state: touch

    - name: Copy a file to Windows
      win_copy:
        src: ~/.ssh/ansible.pub
        dest: "C:\\%USERPROFILE%\\.ssh\\authorized_keys"







