---
- name: Copy Ansible SSH-Key to windows
  hosts: windows_slaves
  gather_facts: no

  vars:
    ansible_become_method: runas
    ansible_become_user: Administrator

  tasks:
    - name: Ping Windows clients
      win_ping:

    - name: Create a directory on Windows
      win_file:
        path: C:\$env:USERPROFILE\.ssh
        state: directory

    - name: Copy a file to Windows
      win_copy:
        src: ~/.ssh/ansible.pub
        dest: C:\$env:USERPROFILE\.ssh\authorized_keys



