---
- name: Copy Ansible SSH-Key to windows
  hosts: windows_slaves
  gather_facts: no
  tasks:

    - name: Get USERPROFILE environment variable
      win_shell: echo $env:USERPROFILE
      register: userprofile_env

    - name: Create a directory on Windows
      win_file:
        path: "{{ userprofile_env.stdout }}\\.ssh"
        state: directory

    - name: Create the authorized key file
      win_file:
        path: "{{ userprofile_env.stdout }}\\.ssh\\authorized_keys"
        state: touch

    - name: Copy a file to Windows
      win_copy:
        src: ~/.ssh/ansible.pub
        dest: "{{ userprofile_env.stdout }}\\.ssh\\authorized_keys"