---
- name: Copy Ansible SSH-Key to windows
  hosts: windows_slaves
  gather_facts: no

  tasks:
    - name: Ping Windows clients
      win_ping:

    - name: Define user profile variable
      set_fact:
        user_profile: "{{ lookup('env', 'USERPROFILE') }}"

    - name: Create a directory on Windows
      win_file:
        path: "C:\\{{ user_profile }}\\.ssh"
        state: directory

    - name: Copy a file to Windows
      win_copy:
        src: ~/.ssh/ansible.pub
        dest: "C:\\{{ user_profile }}\\.ssh\\authorized_keys"







