---
- name: Test playbook for Windows clients
  hosts: windows_slaves
  gather_facts: no
  tasks:
    - name: Ping Windows clients
      win_ping:

    - name: Create a directory on Windows
      win_file:
        path: C:\test_directory
        state: directory

    - name: Copy a file to Windows
      win_copy:
        src: /path/to/local/file.txt
        dest: C:\test_directory\file.txt

    - name: Run a command on Windows
      win_command: |
        echo "Hello, World!" > C:\test_directory\hello.txt
