- name: install apache2 and php packages on Ubuntu
  tags: apache, apache2, php, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache2 and php package for centOS
  tags: CentOS, apache, apache2, php
  dnf:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
