---
- name: Copy SSH public key to LinuxSlaves
  hosts: LinuxSlaves
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure .ssh directory exists for ansible_user
      file:
        path: /home/janina/.ssh
        state: directory
        mode: "0700"

    - name: Copy SSH public key to authorized_keys for ansible_user
      copy:
        src: /home/janina/.ssh/janina.pub
        dest: /home/janina/.ssh/authorized_keys
        mode: "0644"
        append: yes

    - name: Ensure .ssh directory exists for janina
      file:
        path: /home/janina/.ssh
        state: directory
        mode: "0700"

    - name: Copy SSH public key to authorized_keys for janina
      copy:
        src: /home/janina/.ssh/ansible.pub
        dest: /home/janina/.ssh/authorized_keys
        mode: "0644"
        append: yes
